core/controllers/SiteController.php
<?php
/**
 * @link http://simpleforum.org/
 * @copyright Copyright (c) 2015 SimpleForum
 * @author Jiandong Yu admin@simpleforum.org
 */

namespace app\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\Html;
use yii\web\ServerErrorHttpException;
use yii\web\Cookie;
use app\models\LoginForm;
use app\models\ForgotPasswordForm;
use app\models\ResetPasswordForm;
use app\models\ChangeEmailForm;
use app\models\SignupForm;
use app\models\Auth;
use app\models\User;
use app\models\Token;

/**
 * Site controller
 */
class SiteController extends AppController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup', 'forgot-password', 'reset-password'],
                'rules' => [
                    [
                        'actions' => ['signup', 'forgot-password', 'reset-password'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
                'height' => 40,
                'maxLength' => 5,
                'minLength' => 4,
            ],
            'auth' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'onAuthSuccess'],
            ],
        ];
    }

    public function onAuthSuccess($client)
    {
        $sourceName = [
            'weibo'=>'微博',
            'weixin'=>'微信',
        ];
        $me = Yii::$app->getUser();

        $source = $client->getId();
        $attr = $client->getUserAttributes();

        $auth = Auth::findOne([
            'source' => $source,
            'source_id' => (string)$attr['id'],
        ]);

        if ($me->getIsGuest()) {
            if ($auth) { // login
                $user = $auth->user;
                $me->login($user);
            } else { // signup
                $attr['source'] = $source;
//              $attr['sourceName'] = $client->defaultName();
                $attr['sourceName'] = empty($sourceName[$source])?$source:$sourceName[$source];
                $session = Yii::$app->getSession();
                $session->set('authInfo', $attr);
                return $this->redirect(['auth-bind-account']);

            }
        } else { // user already signed in
            if (!$auth) { // add auth provider
                $auth = new Auth([
                    'user_id' => Yii::$app->getUser()->id,
                    'source' => $source,
                    'source_id' => (string)$attr['id'],
                ]);
                $auth->save();
                if(Yii::$app->getRequest()->get('action') === 'bind') {
                    $this->redirect(['my/settings', '#'=>'auth']);
                }
            }
        }
    }

    public function actionAuthSignup()
    {
        $session = Yii::$app->getSession();
        if( !$session->has('authInfo') ) {
            return $this->redirect(['login']);
        }
        $attr = $session->get('authInfo');

        $model = new SignupForm(['action' => SignupForm::ACTION_AUTH_SIGNUP]);
        if ($model->load(Yii::$app->getRequest()->post())) {
            if ($user = $model->signup()) {
                $auth = new Auth([
                    'user_id' => $user->id,
                    'source' => (string)$attr['source'],
                    'source_id' => (string)$attr['id'],
                ]);
                if ($auth->save()) {
                    $session->remove('authInfo');
                } else {
                    throw new ServerErrorHttpException(implode('<br />', $auth->getFirstErrors()));
                }
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
            'authInfo' => $attr,
        ]);
    }

    public function actionAuthBindAccount()
    {
        if (! Yii::$app->getUser()->getIsGuest()) {
            return $this->goHome();
        }

        $session = Yii::$app->getSession();
        if( !$session->has('authInfo') ) {
            return $this->redirect(['login']);
        }
        $attr = $session->get('authInfo');

        $model = new LoginForm(['scenario' => LoginForm::SCENARIO_BIND]);
        if ($model->load(Yii::$app->getRequest()->post()) && $model->login()) {
            $auth = new Auth([
                'user_id' => Yii::$app->getUser()->id,
                'source' => (string)$attr['source'],
                'source_id' => (string)$attr['id'],
            ]);
            if ($auth->save()) {
                $session->remove('authInfo');
            } else {
                throw new ServerErrorHttpException(implode('<br />', $auth->getFirstErrors()));
            }
            return $this->goHome();
        } else {
            return $this->render('authBindAccount', [
                'model' => $model,
                'authInfo' => $attr,
            ]);
        }

    }

    public function actionLanguage()
    {
        $language = Yii::$app->getRequest()->get('language');
        if($language) {
            //Yii::$app->language = $language;
            $languageCookie = new Cookie([
                'name' => 'language',
                'value' => $language,
                'expire' => time() + 60 * 60 * 24 * 30, // 30 days
            ]);
            Yii::$app->getResponse()->getCookies()->add($languageCookie);
        }
        //$this->redirect(['topic/index']);
        return $this->goBack();
    }

    public function actionLogin()
    {
        if (! Yii::$app->getUser()->getIsGuest()) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->getRequest()->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionOffline()
    {
        return $this->render('offline');
    }

    public function actionLogout()
    {
        Yii::$app->getUser()->logout();

        return $this->goHome();
    }

    public function actionSignup()
    {
        if ( intval($this->settings['close_register']) === 1) {
            return $this->render('@app/views/common/info', ['title'=>Yii::t('app', 'Registration Closed'), 'status'=>'success', 'msg'=>Yii::t('app', 'Please use {url} to sign in.', ['url' => \yii\helpers\Html::a(Yii::t('app', 'Third-Party Accounts'), ['site/login'])])]);
        }
        $model = new SignupForm();
        if ($model->load(Yii::$app->getRequest()->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    if ($user->status == User::STATUS_INACTIVE) {
                        return $this->render('@app/views/common/info', ['title'=>Yii::t('app', 'Thank You For Your Registration'), 'status'=>'success', 'msg'=>Yii::t('app', 'An email has been sent to your email address containing an activation link. Please click on the link to activate your account. If you do not receive the email within a few minutes, please check your spam folder.')]);
                    } else if ($user->status == User::STATUS_ADMIN_VERIFY) {
                        return $this->render('@app/views/common/info', ['title'=>Yii::t('app', 'Thank You For Your Registration'), 'status'=>'success', 'msg'=>Yii::t('app', 'Please wait for the admin approval.')]);
                    } else {
                        return $this->goHome();
                    }
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    public function actionForgotPassword()
    {
        try {
            $model = new ForgotPasswordForm();
        } catch (InvalidParamException $e) {
            return $this->render('@app/views/common/info', ['title'=>Yii::t('app', 'Reset Password'), 'status'=>'warning', 'msg'=>$e->getMessage()]);
        }
        if ($model->load(Yii::$app->getRequest()->post()) && $model->validate()) {
            try {
                $model->apply();
                return $this->render('@app/views/common/info', ['title'=>Yii::t('app', 'Reset Password'), 'status'=>'success', 'msg'=>Yii::t('app', 'An email has been sent to your email address containing a verification link. Please click on the link to reset your password. If you do not receive the email within a few minutes, please check your spam folder.')]);
            } catch (InvalidParamException $e) {
                Yii::$app->getSession()->setFlash('sendPwdNG', $e->getMessage());
            }
        }

        return $this->render('forgotPassword', [
            'model' => $model,
        ]);
    }

    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {

core/views/site/authBindAccount.php
<?php
/**
 * @link http://simpleforum.org/
 * @copyright Copyright (c) 2015 SimpleForum
 * @author Jiandong Yu admin@simpleforum.org
 */

use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;

$this->title = Yii::t('app', 'Bind your account');
?>

<div class="row">
<!-- sf-left start -->
<div class="col-lg-8 sf-left">

<div class="card sf-box">
    <div class="card-header sf-box-header sf-navi">
        <?php echo Html::a(Yii::t('app', 'Home'), ['topic/index']), '&nbsp;/&nbsp;', $this->title; ?>
    </div>
    <div class="card-body sf-box-form">
<?php $form = ActiveForm::begin([
            'layout' => 'horizontal',
            'id' => 'form-auth-bind-account',
            'fieldConfig' => [
                'horizontalCssClasses' => [
                    'label' => 'col-form-label col-sm-3 text-sm-right',
                    'wrapper' => 'col-sm-9',
                ],
            ],
      ]); ?>
        <div class="form-group row">
            <div class="offset-sm-3 col-sm-9" style="padding-top:7px;">
                <?php echo Yii::t('app', 'You have signed in with your {name} account.', ['name'=>$authInfo['sourceName']]); ?>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-form-label col-sm-3 text-sm-right"><?php echo Yii::t('app', 'Username'); ?></label>
            <div class="col-sm-9" style="padding-top:7px;">
                <strong><?php echo $authInfo['username']; ?></strong>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-form-label col-sm-3 text-sm-right"><?php echo Yii::t('app', 'Don\'t have an account?'); ?></label>
            <div class="col-sm-9">
                <?php echo Html::a(Yii::t('app', 'Create an account and bind it'), ['auth-signup'], ['class'=>'btn sf-btn']); ?>
            </div>
        </div>
        <br /><strong><?php echo Yii::t('app', 'Bind your account'); ?></strong><hr>
        <?php echo $form->field($model, 'username')->textInput(['maxlength'=>20]); ?>
        <?php echo $form->field($model, 'password')->passwordInput(['maxlength'=>20]); ?>
        <div class="form-group">
            <div class="offset-sm-3 col-sm-9">
            <?php echo Html::submitButton(Yii::t('app', 'Bind'), ['class' => 'btn sf-btn', 'name' => 'login-button']); ?>
            &nbsp;&nbsp;<?php echo Html::a(Yii::t('app', 'Forgot password?'), ['site/forgot-password']); ?>
            </div>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>

</div>
<!-- sf-left end -->

<!-- sf-right start -->
<div class="col-lg-4 sf-right">
<?php echo $this->render('@app/views/common/_right'); ?>
</div>
<!-- sf-right end -->

</div>

core/views/site/error.php
<?php
/**
 * @link http://simpleforum.org/
 * @copyright Copyright (c) 2015 SimpleForum
 * @author Jiandong Yu admin@simpleforum.org
 */

use yii\helpers\Html;

$session = Yii::$app->getSession();

$this->title = Yii::t('app', 'Error occurred');
?>

<div class="row">
<!-- sf-left start -->
<div class="col-lg-8 sf-left">

<div class="card sf-box">
    <div class="card-header sf-box-header sf-navi">
        <?php echo Html::a(Yii::t('app', 'Home'), ['topic/index']), '&nbsp;/&nbsp;', $this->title; ?>
    </div>
    <div class="card-body">
        <p><strong><?php echo Html::encode($name); ?></strong></p>
        <div class="alert alert-danger">
            <?php echo nl2br(Html::encode($message)); ?>
        </div>
        <p><?php echo Yii::t('app', 'The above error occurred while the Web server was processing your request.'); ?></p>
        <p><?php echo Yii::t('app', 'Please contact administrator if you think this is a server error. Thank you.'); ?></p>
    </div>
</div>

</div>
<!-- sf-left end -->

<!-- sf-right start -->
<div class="col-lg-4 sf-right">
<?php echo $this->render('@app/views/common/_right'); ?>
</div>
<!-- sf-right end -->

</div>

core/views/site/forgotPassword.php
<?php
/**
 * @link http://simpleforum.org/
 * @copyright Copyright (c) 2015 SimpleForum
 * @author Jiandong Yu admin@simpleforum.org
 */

use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Alert;

$session = Yii::$app->getSession();

$this->title = Yii::t('app', 'Reset your password');
?>

<div class="row">
<!-- sf-left start -->
<div class="col-lg-8 sf-left">

<div class="card sf-box">
    <div class="card-header sf-box-header sf-navi">
        <?php echo Html::a(Yii::t('app', 'Home'), ['topic/index']), '&nbsp;/&nbsp;', $this->title; ?>
    </div>
    <div class="card-body sf-box-form">
<?php
if ( $session->hasFlash('sendPwdNG') ) {
echo Alert::widget([
       'options' => ['class' => 'alert-warning'],
       'body' => Yii::t('app', $session->getFlash('sendPwdNG')),
    ]);
}
?>
        <?php $form = ActiveForm::begin([
            'layout' => 'horizontal',
            'id' => 'form-fogot-password',
            'fieldConfig' => [
                'horizontalCssClasses' => [
                    'label' => 'col-form-label col-sm-3 text-sm-right',
                    'wrapper' => 'col-sm-9',
                ],
            ],
        ]); ?>
            <?php echo $form->field($model, 'email')->textInput(['maxlength'=>50]); ?>
            <div class="form-group">
            <div class="offset-sm-3 col-sm-9">
                    <?php echo Html::submitButton(Yii::t('app', 'Send password reset email'), ['class' => 'btn sf-btn']); ?>
        </div>
            </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>

</div>
<!-- sf-left end -->

<!-- sf-right start -->
<div class="col-lg-4 sf-right">
<?php echo $this->render('@app/views/common/_right'); ?>
</div>
<!-- sf-right end -->

</div>

core/views/site/login.php
<?php
/**
 * @link http://simpleforum.org/
 * @copyright Copyright (c) 2015 SimpleForum
 * @author Jiandong Yu admin@simpleforum.org
 */

use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Alert;

$session = Yii::$app->getSession();

$this->title = Yii::t('app', 'Sign in');
?>

<div class="row">
<!-- sf-left start -->
<div class="col-lg-8 sf-left">

<div class="card sf-box">
    <div class="card-header sf-box-header sf-navi">
        <?php echo Html::a(Yii::t('app', 'Home'), ['topic/index']), '&nbsp;/&nbsp;', $this->title; ?>
    </div>
    <div class="card-body sf-box-form">
<?php
if ( $session->hasFlash('accessNG') ) {
echo Alert::widget([
       'options' => ['class' => 'alert-warning'],
       'body' => Yii::t('app', $session->getFlash('accessNG')),
    ]);
}
?>
<?php $form = ActiveForm::begin([
          'layout' => 'horizontal',
          'id' => 'form-login',
          'fieldConfig' => [
              'horizontalCssClasses' => [
                  'label' => 'col-form-label col-sm-3 text-sm-right',
                  'wrapper' => 'col-sm-9',
              ],
          ],
      ]); ?>
        <?php echo $form->field($model, 'username')->textInput(['maxlength'=>20]); ?>
        <?php echo $form->field($model, 'password')->passwordInput(['maxlength'=>20]); ?>
        <?php echo $form->field($model, 'rememberMe', [
                       'horizontalCssClasses' => [
                           'offset' => 'offset-sm-3',
                       ]
                   ])->checkbox(); ?>
        <?php
        $captcha = ArrayHelper::getValue(Yii::$app->params, 'settings.captcha', '');
        if(!empty($captcha) && ($plugin=ArrayHelper::getValue(Yii::$app->params, 'plugins.' . $captcha, []))) {
            $plugin['class']::captchaWidget('signin', $form, $model, null, $plugin);
        }
        ?>

        <div class="form-group">
            <div class="offset-sm-3 col-sm-9">
            <?php echo Html::submitButton(Yii::t('app', 'Sign in'), ['class' => 'btn sf-btn', 'name' => 'login-button', 'id'=>'recaptchaToken']); ?>
            &nbsp;&nbsp;<?php echo Html::a(Yii::t('app', 'Forgot password?'), ['site/forgot-password']); ?>
            </div>
        </div>
        <?php ActiveForm::end(); ?>
<?php if ( intval(Yii::$app->params['settings']['auth_enabled']) === 1 ) : ?>
        <h6 class="third-party-login-msg"><strong><?php echo Yii::t('app', 'Third-party login'); ?></strong></h6>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 third-party-login">
        <?php
foreach (Yii::$app->authClientCollection->getClients() as $client){
    echo '<div class="col ' .$client->getId() . '">';
    if ($client->getId() == 'weixin' && $client->type == 'mp') {
        echo Html::a('<i class="fab fa-'.$client->getId().'"></i><span class="snstext">'. Html::encode($client->getTitle()) . '</span>', '#', ['onclick'=>'return false;', 'class'=>'btn auth-link '. $client->getId(), 'id'=>'weixinmp', 'link'=>Url::to(['site/auth', 'authclient'=>$client->getId()], true)]);
    } else {
        echo Html::a('<i class="fab fa-'.$client->getId().'"></i><span class="snstext">'. Html::encode($client->getTitle()) . '</span>', ['site/auth', 'authclient'=>$client->getId()], ['class'=>'btn auth-link '. $client->getId(), 'title'=>Html::encode($client->getTitle())]);
    }
    echo '</div>';
}
        ?></div>
<?php endif; ?>
    </div>
</div>

</div>
<!-- sf-left end -->

<!-- sf-right start -->
<div class="col-lg-4 sf-right">
<?php echo $this->render('@app/views/common/_right'); ?>
</div>
<!-- sf-right end -->

</div>

core/views/site/offline.php
<?php
/**
 * @link http://simpleforum.org/
 * @copyright Copyright (c) 2015 SimpleForum
 * @author Jiandong Yu admin@simpleforum.org
 */

use yii\helpers\Html;
use yii\bootstrap4\Alert;

$this->title = Yii::t('app', 'Forum under maintenance');
?>

<div class="row">
<!-- sf-left start -->
<div class="col-lg-8 sf-left">

<div class="card sf-box">
	<div class="card-header sf-box-header sf-navi">
		<?php echo Html::a(Yii::t('app', 'Home'), ['topic/index']), '&nbsp;/&nbsp;', $this->title; ?>
	</div>
	<div class="card-body">
<?php echo Alert::widget([
   'options' => ['class' => 'alert-danger'],
   'closeButton'=>false,
   'body' => Yii::$app->params['settings']['offline_msg'],
]);
?>
	</div>
</div>

</div>
<!-- sf-left end -->

<!-- sf-right start -->
<div class="col-lg-4 sf-right">
<?php echo $this->render('@app/views/common/_right'); ?>
</div>
<!-- sf-right end -->

</div>

core/views/site/resetPassword.php
<?php
/**
 * @link http://simpleforum.org/
 * @copyright Copyright (c) 2015 SimpleForum
 * @author Jiandong Yu admin@simpleforum.org
 */

use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;

$this->title = Yii::t('app', 'Reset your password');
?>

<div class="row">
<!-- sf-left start -->
<div class="col-lg-8 sf-left">

<div class="card sf-box">
    <div class="card-header sf-box-header sf-navi">
        <?php echo Html::a(Yii::t('app', 'Home'), ['topic/index']), '&nbsp;/&nbsp;', $this->title; ?>
    </div>
    <div class="card-body sf-box-form">
        <?php $form = ActiveForm::begin([
            'layout' => 'horizontal',
            'id' => 'form-reset-password'
        ]); ?>
            <?php echo $form->field($model, 'password')->passwordInput(['maxlength'=>20]); ?>
            <?php echo $form->field($model, 'password_repeat')->passwordInput(['maxlength'=>20]); ?>
            <div class="form-group">
                <div class="offset-sm-3 col-sm-9">
                <?php echo Html::submitButton(Yii::t('app', 'Submit'), ['class' => 'btn sf-btn']); ?>
                </div>
            </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>

</div>
<!-- sf-left end -->

<!-- sf-right start -->
<div class="col-lg-4 sf-right">
<?php echo $this->render('@app/views/common/_right'); ?>
</div>
<!-- sf-right end -->

</div>

core/views/site/signup.php
<?php
/**
 * @link http://simpleforum.org/
 * @copyright Copyright (c) 2015 SimpleForum
 * @author Jiandong Yu admin@simpleforum.org
 */

use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;
use app\models\SignupForm;


if ($model->action === SignupForm::ACTION_AUTH_SIGNUP) {
    $this->title = Yii::t('app', 'Create an account and bind a third-party account');
    $btnLabel = Yii::t('app', 'Create an account and bind it');
} else {
    $this->title = Yii::t('app', 'Sign up');
    $btnLabel = $this->title;
}
?>

<div class="row">
<!-- sf-left start -->
<div class="col-lg-8 sf-left">

<div class="card sf-box">
    <div class="card-header sf-box-header sf-navi">
        <?php echo Html::a(Yii::t('app', 'Home'), ['topic/index']), '&nbsp;/&nbsp;', $this->title; ?>
    </div>
    <div class="card-body sf-box-form">
<?php $form = ActiveForm::begin([
            'layout' => 'horizontal',
            'id' => 'form-signup',
            'fieldConfig' => [
              'horizontalCssClasses' => [
                  'label' => 'col-form-label col-sm-3 text-sm-right',
                  'wrapper' => 'col-sm-9',
              ],
            ],
        ]); ?>
<?php if ($model->action === SignupForm::ACTION_AUTH_SIGNUP) : ?>
        <div class="form-group row">
            <div class="offset-sm-3 col-sm-9">
                <?php echo Yii::t('app', 'You have signed in with your {name} account.', ['name'=>$authInfo['sourceName']]); ?>
            </div>
        </div>
        <div class="form-group row">
            <label class="control-label col-sm-3 text-sm-right"><?php echo Yii::t('app', 'Username'); ?></label>
            <div class="col-sm-9">
                <strong><?php echo $authInfo['username']; ?></strong>
            </div>
        </div>
        <div class="form-group row">
            <label class="control-label col-sm-3 text-sm-right"><?php echo Yii::t('app', 'Have an account?'); ?></label>
            <div class="col-sm-9">
                <?php echo Html::a(Yii::t('app', 'Bind your account'), ['auth-bind-account'], ['class'=>'btn sf-btn']); ?>
            </div>
        </div>
        <br /><strong><?php echo Yii::t('app', 'Create an account'); ?></strong><hr>
<?php endif; ?>
            <?php echo $form->field($model, 'username')->textInput(['maxlength'=>16])->hint(Yii::t('app', 'letters, numbers and \'_\'')); ?>
            <?php echo $form->field($model, 'name')->textInput(['maxlength'=>40])->hint(Yii::t('app', 'display name')); ?>
            <?php echo $form->field($model, 'email')->textInput(['maxlength'=>50]); ?>
            <?php echo $form->field($model, 'password')->passwordInput(['maxlength'=>20]); ?>
            <?php echo $form->field($model, 'password_repeat')->passwordInput(['maxlength'=>20]); ?>
<?php
if ( intval(Yii::$app->params['settings']['close_register']) === 2 ) {
    echo $form->field($model, 'invite_code')->textInput(['maxlength'=>6]);
}
        $captcha = ArrayHelper::getValue(Yii::$app->params, 'settings.captcha', '');
        if(!empty($captcha) && ($plugin=ArrayHelper::getValue(Yii::$app->params, 'plugins.' . $captcha, []))) {
            $plugin['class']::captchaWidget('signup', $form, $model, null, $plugin);
        }
?>
            <div class="form-group">
                <div class="offset-sm-3 col-sm-9">
                <?php echo Html::submitButton($btnLabel, ['class' => 'btn sf-btn', 'name' => 'signup-button']); ?>
                </div>
            </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>

</div>
<!-- sf-left end -->

<!-- sf-right start -->
<div class="col-lg-4 sf-right">
<?php echo $this->render('@app/views/common/_right'); ?>
</div>
<!-- sf-right end -->

</div>